apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-p1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.nsf-server.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-app-claim
spec:
  storageClassName: "" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-p2
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.nsf-server.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-nginx-claim
spec:
  storageClassName: "" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-p3
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.nsf-server.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-le-claim
spec:
  storageClassName: "" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-p4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.nsf-server.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-logs-claim
spec:
  storageClassName: "" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
