name: Publish Docker Image

on:
  push:
    branches:
      - "develop"
      - "release/v*"

  workflow_dispatch:

jobs:
  push:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-20.04
    # Always run against a tag, even if the commit into the tag has [docker skip]
    # within the commit message.
    if: "!contains(github.ref, 'develop') || (!contains(github.event.head_commit.message, 'skip docker') && !contains(github.event.head_commit.message, 'docker skip'))"
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Release development build
        uses: docker/build-push-action@v2
        if: "contains(github.ref, 'develop')"
        with:
          context: .
          file: ./Dockerfile
          push: false         #${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: pterodactyl:dev

      - name: ðŸš€ Push Image to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          push_only: true
          registry: gcr.io
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          image_name: pterodactyl
          image_tag: dev


      # - name: Release production build
      #   uses: docker/build-push-action@v2
      #   if: "contains(github.ref, 'release/v')"
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: ${{ steps.docker_meta.outputs.tags }}
      #     labels: ${{ steps.docker_meta.outputs.labels }}

